### PR TITLE
Add GPL-3.0 license

### LINKED ISSUE #83: Missing license
Hi,

There seems to be no license for this code repository.

### PR DESCRIPTION
**Pull request by haveyaseen**
I hereby agree that the code that has been published in this repository shall be licensed under the GPL v3.0 License.

I would like to ask all contributors to agree to the same here.

Closes #83.

### CODE REVIEW

**Comment by NicklasKnell** [comment]
I hereby agree that the code that has been published in this repository shall be licensed under the GPL v3.0 License.

**Comment by wilgert** [comment]
I hereby agree that the code that has been published in this repository shall be licensed under the GPL v3.0 License.

**Comment by haveyaseen** [comment]
@lonnv We also need your permission to move forward on this :slightly_smiling_face:

**Comment by lonnv** [comment]
I agree

**Comment by kreativmonkey** [comment]
i missed in this vote but i'm fine with the changes. Github not show me at contributor but i contribute a few lines of code to the app...

**Comment by fwolfst** [comment]
:) Now, it would have been a good idea to say "or any later version" (AGPLv3+). Probably your code will not move into the problematic "linking" area, but imho when using *GPL (which would have been my choice too) it is always a good idea to include the "or any later version" phrasing.

**Pull request merged**
